### ISSUE TITLE
BUG: 可以購買零項商品

### ISSUE THREAD

**Issue by KageRyo** [rumamitw01/Vue_Shopping#1]
# BUG: 可以購買零項商品
![image](https://github.com/user-attachments/assets/7f2e45bb-6ba7-4ec8-9782-939b794cd1c4)
![image](https://github.com/user-attachments/assets/00506e69-4cbf-4946-88ca-766f85c45308)
![image](https://github.com/user-attachments/assets/2271e0aa-5c73-4e5d-926d-fd4a5e2987ab)
## 點選商品數量為 0 時，應該禁止使用者將其加入購物車

**Comment by rumamitw01** [comment]
不太想修期末報告(X

**Comment by rumamitw01** [comment]
Bug修復完成
